on:
  release:
    types: [published]

jobs:
  release_windows_x64:
    runs-on: ubuntu-latest
    steps:
      - name: download Windows x64
        id: download-windows-x64
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "latest"
          file: hs-windows-x64.zip
          token: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (Windows 64bit)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: hungry-snake
          ITCH_USER: dancovich
          PACKAGE: hs-windows-x64.zip
          VERSION: ${{ steps.download-windows-x64.outputs.version }}
  release_macos:
    runs-on: ubuntu-latest
    steps:
      - name: download MacOS
        id: download-macos
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "latest"
          file: hs-macosx.zip
          token: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (MacOS)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: mac
          ITCH_GAME: hungry-snake
          ITCH_USER: dancovich
          PACKAGE: hs-macosx.zip
          VERSION: ${{ steps.download-macos.outputs.version }}
  release_linux:
    runs-on: ubuntu-latest
    steps:
      - name: download Linux
        id: download-linux
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "latest"
          file: hs-linux-x64.zip
          token: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (Linux)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: hungry-snake
          ITCH_USER: dancovich
          PACKAGE: hs-linux-x64.zip
          VERSION: ${{ steps.download-linux.outputs.version }}
  release_html:
    runs-on: ubuntu-latest
    steps:
      - name: download HTML5
        id: download-html
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "latest"
          file: hs-html.zip
          token: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (HTML5)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html
          ITCH_GAME: hungry-snake
          ITCH_USER: dancovich
          PACKAGE: hs-html.zip
          VERSION: ${{ steps.download-html.outputs.version }}